apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: orders-hpa
  namespace: orders
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: orders-deployment
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 50
