apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: orders-aws-secrets
  namespace: orders
spec:
  provider: aws
  secretObjects:
    - secretName: orders-db-secrets
      type: Opaque
      data:
        - objectName: endpoint
          key: endpoint
        - objectName: name
          key: name
        - objectName: username
          key: username
        - objectName: password
          key: password
    - secretName: cognito-secrets
      type: Opaque
      data:
        - objectName: "issuer-uri"
          key: "issuer-uri"
        - objectName: "jwk-set-uri"
          key: "jwk-set-uri"
  parameters:
    region: us-east-1
    objects: |
      - objectName: "/live/cognito"
        objectType: "ssmparameter"
        jmesPath:
          - path: "issuer-uri"
            objectAlias: "issuer-uri"
          - path: "jwk-set-uri"
            objectAlias: "jwk-set-uri"
      - objectName: "/live/orders/db"
        objectType: "ssmparameter"
        jmesPath:
          - path: "endpoint"
            objectAlias: "endpoint"
          - path: "name"
            objectAlias: "name"
      - objectName: "arn:aws:secretsmanager:us-east-1:202062340677:secret:rds!db-dc8efc99-0171-4803-b686-957bb74148e0-2cwFSE"
        jmesPath:
          - path: "username"
            objectAlias: "username"
          - path: "password"
            objectAlias: "password"
