apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-deployment
  namespace: stock
  labels:
    app: stock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock
  template:
    metadata:
      namespace: stock
      labels:
        app: stock
    spec:
      serviceAccountName: stock-service-account
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: stock-aws-secrets
      containers:
        - name: stock
          image: 202062340677.dkr.ecr.us-east-1.amazonaws.com/fiap-3soat-g15-stock-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "200m"
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            periodSeconds: 30
            failureThreshold: 10
            initialDelaySeconds: 20
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            periodSeconds: 30
            failureThreshold: 10
            initialDelaySeconds: 20
            timeoutSeconds: 5
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: live
            - name: DB_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: stock-db-secrets
                  key: endpoint
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: stock-db-secrets
                  key: name
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: stock-db-secrets
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: stock-db-secrets
                  key: password
            - name: ADMIN_ACCESS_TOKEN
              value: token
