apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: stock-hpa
  namespace: stock
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: stock-deployment
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 50
