apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: stock-aws-secrets
  namespace: stock
spec:
  provider: aws
  secretObjects:
    - secretName: stock-db-secrets
      type: Opaque
      data:
        - objectName: endpoint
          key: endpoint
        - objectName: name
          key: name
        - objectName: username
          key: username
        - objectName: password
          key: password
  parameters:
    region: us-east-1
    objects: |
      - objectName: "/live/stock/db"
        objectType: "ssmparameter"
        jmesPath:
          - path: "endpoint"
            objectAlias: "endpoint"
          - path: "name"
            objectAlias: "name"
      - objectName: "arn:aws:secretsmanager:us-east-1:202062340677:secret:rds!db-9fc858e2-c608-4835-a335-3fc95939dae9-RrwZOT"
        jmesPath:
          - path: "username"
            objectAlias: "username"
          - path: "password"
            objectAlias: "password"
