apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: payments-aws-secrets
  namespace: payments
spec:
  provider: aws
  secretObjects:
    - secretName: payments-mercado-pago-secrets
      type: Opaque
      data:
        - objectName: token
          key: token
        - objectName: userId
          key: userId
        - objectName: posId
          key: posId
        - objectName: webhookBaseUrl
          key: webhookBaseUrl
    - secretName: cognito-secrets
      type: Opaque
      data:
        - objectName: issueruri
          key: issueruri
        - objectName: jwkseturi
          key: jwkseturi
  parameters:
    region: us-east-1
    objects: |
      - objectName: "/live/cognito"
        objectType: "ssmparameter"
        jmesPath:
          - path: "issueruri"
            objectAlias: "issueruri"
          - path: "jwkseturi"
            objectAlias: "jwkseturi"
      - objectName: "live/payments/mercadopago"
        objectType: "secretsmanager"
        jmesPath:
          - path: "token"
            objectAlias: "token"
          - path: "userId"
            objectAlias: "userId"
          - path: "posId"
            objectAlias: "posId"
          - path: "webhookBaseUrl"
            objectAlias: "webhookBaseUrl"
