apiVersion: apps/v1
kind: Deployment
metadata:
  name: self-order-management
  namespace: tech-challenge
  labels:
    app: self-order-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: self-order-management
  template:
    metadata:
      namespace: selfordermanagement
      labels:
        app: self-order-management
    spec:
      serviceAccountName: tech-challenge-service-account
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: self-order-management-aws-secrets
      containers:
        - name: self-order-management
          image: 202062340677.dkr.ecr.us-east-1.amazonaws.com/tech-challenge:latest
          imagePullPolicy: IfNotPresent
          
          ports:
            - containerPort: 8080
              
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "200m"
              
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
              
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            periodSeconds: 30
            failureThreshold: 10
            initialDelaySeconds: 20
            timeoutSeconds: 5
            
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            periodSeconds: 30
            failureThreshold: 10
            initialDelaySeconds: 20
            timeoutSeconds: 5
            
          env:
            - name: DB_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: endpoint
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: name
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: password
            - name: ADMIN_ACCESS_TOKEN
              value: token
            - name: MOCK_PAYMENT_PROVIDER
              value: "true"
            - name: MP_TOKEN
              valueFrom:
                secretKeyRef:
                  name: mp-secrets
                  key: token
            - name: MP_USER_ID
              valueFrom:
                secretKeyRef:
                  name: mp-secrets
                  key: userId
            - name: MP_POS_ID
              valueFrom:
                secretKeyRef:
                  name: mp-secrets
                  key: posId
            - name: MP_WEBHOOK_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: mp-secrets
                  key: webhookBaseUrl
