apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: self-order-management
  namespace: tech-challenge
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: self-order-management
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 50
