apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: self-order-management-aws-secrets
  namespace: tech-challenge
spec:
  provider: aws
  secretObjects:
    - secretName: db-secrets
      type: Opaque
      data:
        - objectName: endpoint
          key: endpoint
        - objectName: name
          key: name
        - objectName: username
          key: username
        - objectName: password
          key: password
    - secretName: mp-secrets
      type: Opaque
      data:
        - objectName: token
          key: token
        - objectName: userId
          key: userId
        - objectName: posId
          key: posId
        - objectName: webhookBaseUrl
          key: webhookBaseUrl
  parameters:
    region: us-east-1
    objects: |
      - objectName: "/live/selfordermanagement/db"
        objectType: "ssmparameter"
        jmesPath:
          - path: "endpoint"
            objectAlias: "endpoint"
          - path: "name"
            objectAlias: "name"
      - objectName: "arn:aws:secretsmanager:us-east-1:202062340677:secret:rds!db-f353f366-e5ec-495d-b513-233db1028ab3-SG2Onk"
        jmesPath:
          - path: "username"
            objectAlias: "username"
          - path: "password"
            objectAlias: "password"
      - objectName: "live/selfordermanagement/mercadopago"
        objectType: "secretsmanager"
        jmesPath:
          - path: "token"
            objectAlias: "token"
          - path: "userId"
            objectAlias: "userId"
          - path: "posId"
            objectAlias: "posId"
          - path: "webhookBaseUrl"
            objectAlias: "webhookBaseUrl"
