apiVersion: v1
kind: Service
metadata:
  name: self-order-management
  namespace: selfordermanagement
  labels:
    app: self-order-management
spec:
  type: NodePort
  selector:
    app: self-order-management
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31300
