name: "Manifest"

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/manifest.yml
      - 'manifests/**'
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/manifest.yml
      - 'manifests/**'

jobs:
  manifest:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./manifests
    permissions:
      id-token: write
      contents: read
      pull-requests: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::202062340677:role/TechChallengeEKSDeployer
          aws-region: ${{ vars.AWS_REGION }}

      - name: Update kubeconfig
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: aws eks update-kubeconfig --name ${{ vars.AWS_EKS_CLUSTER_NAME }} --region ${{ vars.AWS_REGION }}

      - name: Deploy to EKS
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          kubectl apply -f secret-provider.yml
          kubectl apply -f hpa.yml
          kubectl apply -f deployment.yml
          kubectl apply -f service.yml
          kubectl apply -f load-balancer.yml
